site_name: 国光的 PVE 环境搭建教程
site_url: https://pve.sqlsec.com
site_author: 国光
site_description: "国光的 PVE 环境搭建教程"
repo_name: sqlsec/PVE
repo_url: https://github.com/sqlsec/PVE
copyright: Copyright &copy;  国光
theme:
  name: material
  custom_dir: overrides
  font: false
  language: zh
  icon:
    logo: fontawesome/brands/linux
    repo: fontawesome/brands/git-alt
  favicon: https://image.3001.net/images/20200922/16007336487809.jpg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate 
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换浅色模式
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - git-revision-date
  - search:
      prebuild_index: true
      lang:
        - en
        - ja
  - glightbox
edit_uri: edit/main/docs/
extra:
  generator: false
  social:
    - icon: fontawesome/brands/redhat
      link: https://www.sqlsec.com
      name: 国光
nav:
  - "index.md"
  - 准备工作:
    - 硬件配置: "1/1.md"
    - 系统选择: "1/2.md"
    - 磁盘划分: "1/3.md"
    - 架构规划: "1/4.md"
  - PVE 基础:
    - BIOS设置: "2/1.md"
    - 系统安装: "2/2.md"
    - 基础设置: "2/3.md"
    - 常用命令: "2/4.md"
    - 来宾代理: "2/5.md"
    - 华南排错: "2/6.md"
  - 网络划分:
    - 网络架构: "3/1.md"
    - 网络实战: "3/2.md"
  - PEV 进阶:
    - 添加硬盘: "4/1.md"
    - 硬件直通: "4/2.md"
    - 配置证书: "4/3.md"
    - 硬盘迁移: "4/4.md"
    - vGPU教程: "4/5.md"
    - 功耗节能: "4/6.md"
  - 软路由:
    - 基本操作: "5/1.md"
    - 硬盘扩容: "5/2.md"
    - OpenClash: "5/3.md"
    - IPv6 配置: "5/4.md"
  - 黑群晖:
    - 基本安装: "6/1.md"
    - 存储划分: "6/2.md"
    - SSD缓存: "6/3.md"
    - CPU修正: "6/4.md"
    - 直通独显: "6/5.md"
    - 远程访问: "6/6.md"
    - 添加证书: "6/7.md"
    - WebDAV: "6/8.md"
    - 安装 alist: "6/9.md"
    - 终端美化: "6/10.md"
    - Docker与IPv6: "6/11.md"
  - 黑苹果:
    - 准备工作: "7/1.md"
    - 修正配置: "7/2.md"
    - 系统安装: "7/3.md"
    - 系统优化: "7/4.md" 
  - 远程穿透:
    - NAT类型: "8/1.md"
    - ZeroTier: "8/2.md"
    - IPv6 DDNS: "8/3.md"
    - 远程桌面: "8/4.md"
  - IPv6 专题:
    - IPv6 基础: "9/1.md"
    - IPv6 场景: "9/2.md"
    - IPv6 使用: "9/3.md"
    - IPv6 普及: "9/4.md"
    - IPv6与光猫: "9/5.md"